hooks:
  - repo: wenzm/hello-springboot
    secret: secretkey
    taskinfo:
      namespace: demo
      taskrefname: my-appsody-build
      gitsourceresourcename: hello-springboot-git-source
      dockerimageresourcename: hello-springboot-registry-image
